### ISSUE TITLE
Documentation. Itemize system-variables that do not have a standard name.

### ISSUE THREAD

**Issue by mvac7** [Fubukimaru/asMSX#100]
## Description

Sorry for my bad English. 

The BIOSVARS directive defines a list of variables based on the one defined in [Grauw's MSX Assembly Page](http://map.grauw.nl/resources/msxsystemvars.php). The variables _(or would it be better to call them constants?)_ found in the BIOS, most do not have a defined name.

Currently, the only way to query the name of these variables is to look for them in the source in the **msx_bios_vars()** function in [**dura.y**](https://github.com/Fubukimaru/asMSX/blob/master/src/dura.y) (as indicated in the document).

It would make it easy to add a list of these variables to the document [`2.5. Directives`](https://github.com/Fubukimaru/asMSX/blob/master/doc/asmsx.md), where the `.BIOSVARS` directive is described.

Thanks for readme.

### BIOS System Variables

| Name | Address |
| :--- | ---: |
| CGTABL | $0004 |
| VDP_DR | $0006 |
| VDP_DW | $0007 |
| MSXID1 | $002B |
| MSXID2 | $002C |
| MSXID3 | $002D |

```
| Name | Address |
| :--- | ---: |
| CGTABL | $0004 |
| VDP_DR | $0006 |
| VDP_DW | $0007 |
| MSXID1 | $002B |
| MSXID2 | $002C |
| MSXID3 | $002D |
```

**Comment by duhow** [comment]
Thanks for your comment!
As you already mentioned, this information is already shared in docs here: 

https://github.com/Fubukimaru/asMSX/blob/8b401c7a9041bf38dcbb72d8f33d41440b7cf236/doc/asmsx.md?plain=1#L555-L557

Can you create a pull request with the proposed change?

**Comment by Fubukimaru** [comment]
I have put all the variables there :1234:
