### ISSUE TITLE
[BUG] Why this behaviour? PepeIssue [DIRECTIVES ORDER] diferent results, best persona

### ISSUE THREAD

**Issue by jamque** [Fubukimaru/asMSX#121]
**Describe the bug**
START and ROM directives have different behaviours if you put them after or before PAGE 1

**Expected output**
A ROM file 8ks size regardless START and ROM directives position

**Current output**
A ROM file 24ks size and bad ROM direction after header "AB" bytes or A ROM file 8ks size.

**Code**
Generates a 8k size rom file
```assembly

	ZILOG
	BIOS

	
	PAGE 1
	START MAIN
	ROM
; -----------------------------
MAIN:
	ld	A,1
	ld	(VARIABLE),A
	jp LOOP
; -----------------------------
	PAGE 3
VARIABLE:	byte
```
Generates a 24k size rom file
```assembly

	ZILOG
	BIOS
	START MAIN
	ROM
	
	PAGE 1

; -----------------------------
MAIN:
	ld	A,1
	ld	(VARIABLE),A
	jp LOOP
; -----------------------------
	PAGE 3
VARIABLE:	byte
	
```

**Additional context**
The Game

**Comment by duhow** [comment]
@Fubukimaru yo haría un par de test-case basados en el código, para que, ya que este funcionamiento es el esperado, el comportamiento no cambie en el futuro
