### ISSUE TITLE
END statement missing

### ISSUE THREAD

**Issue by carlos-olivi** [Fubukimaru/asMSX#125]
It seems that there is no END command to stop the compiler. I think it is useful when you want to disconsider part of code.

**Comment by Fubukimaru** [comment]
Hi Carlos!

Thank you for the interest. Is this what you request? https://k1.spdns.de/Develop/Projects/zasm/Documentation/z63.htm#A

I am not really sure if this instruction leads to good coding practices. I would make use of the IF instruction and conditionally remove the parts of the code that we want to disconsider. What do you think?

Also, if you're able to do so, you're welcome to contribute!

**Comment by carlos-olivi** [comment]
Hi! Yes, it is. Maybe you're right about good coding practices. Unfortunately I'm not able to contribute to the code now. I will try to use IF when necessary. Thank you for answer!
