### ISSUE TITLE
mine.asm example builds different on Windows and on Linux

### ISSUE THREAD

**Issue by oboroc** [Fubukimaru/asMSX#14]
I built all examples in code directory on both Windows (asMSX built with MinGW GCC 5.3.0 32-bit) and Linux (Windows 10 Linux subsystem and Ubuntu 16.10 in Hyper-V VM). mine.asm assembles to different ROM file between Windows and Linux.

It's not likely to be 32-bit vs 64-bit issue, because on Linux, both 32-bit and 64-bit builds of asMSX produced the same binary.

I ran the following commands:

```
xxd mine-lin.bin mine-lin.hex
xxd mine-win.bin mine-win.hex
vimdiff mine-lin.hex mine-win.hex
```

It gave me this result:

![mine-bug-vimdiff](https://cloud.githubusercontent.com/assets/3418650/22633664/81b69cf6-ebf1-11e6-8f3c-b2f1ebd1059c.png)

[mine-bin-lin-win.zip](https://github.com/Fubukimaru/asMSX/files/753569/mine-bin-lin-win.zip)

**Comment by oboroc** [comment]
Never mind, it is expected behavior and is due to this code:

```
; Random number tables
RAND_TABLE:
rept 128
 db random (1Eh)+1
endr

```

**Comment by oboroc** [comment]
I decided to reopen this issue, because having non-deterministic random bytes in assembled files could create multiple "unique" versions of the same program and end up in GoodMSX and similar rom sets.

The solution is to use a private random function that produces the same results across platforms and compilers is seeded the same.

**Comment by oboroc** [comment]
Proposed fix: https://github.com/Fubukimaru/asMSX/pull/15

Use a cross-platform d_rand() function, compatible with typical rand() implementation:
```
PSEUDO_RANDOM '(' valor ')' {for (;($$=d_rand()&0xff)>=$3;);}
```

```
#define D_RAND_MAX 32767
static unsigned long int rand_seed = 1;

int d_rand() {
    rand_seed = (rand_seed * 1103515245 + 12345);
    return (unsigned int)(rand_seed/65536) % (D_RAND_MAX + 1);
}
```

**Comment by Fubukimaru** [comment]
Done. Thanks!
