### ISSUE TITLE
Unterminated string on includes

### ISSUE THREAD

**Issue by ghost** [Fubukimaru/asMSX#26]
If an include has a space after the quotes, it returns an "Unterminated string" error.

For example:
.INCLUDE "LIB/TEST.GEN"_ 

Where _ is a whitespace, it returns this error. Otherwise it works properly.

Check grammar/text preprocess.

**Comment by Fubukimaru** [comment]
Hotfix provided in version 0.18.4.
This needs a better fix using the grammar.

**Comment by duhow** [comment]
2111bd285710e95e0eefac67f127abe222cbce5a

**Comment by Fubukimaru** [comment]
This fix is fine.
