### ISSUE TITLE
Zilog -z flag is not passed to dura.y grammar processing.

### ISSUE THREAD

**Issue by ghost** [Fubukimaru/asMSX#28]
This is not normative and may induce to error if other assemblers don't support it.

**Comment by Fubukimaru** [comment]
It's allowed if not using .ZILOG or -z.

HOWEVER. -z fails on setting the zilog variable that is set. yyparse (dura.y), doesn't have the proper zilog value.

**Comment by Fubukimaru** [comment]
This was fixed using a global state struct, which at some point we should remove.
