### ISSUE TITLE
Modify ~tmppre.* files management

### ISSUE THREAD

**Issue by Fubukimaru** [Fubukimaru/asMSX#31]
Instead use http://www.gnu.org/software/libc/manual/html_node/Temporary-Files.html as suggested by @oboroc.

**Comment by oboroc** [comment]
you probably better use C library functions for temp dir and file names: tmpfile() / tempnam() etc.:

http://www.gnu.org/software/libc/manual/html_node/Temporary-Files.html

**Comment by Fubukimaru** [comment]
Oh, very cool :).

I'll add it to the description and change the title

**Comment by Fubukimaru** [comment]
ads

**Comment by Fubukimaru** [comment]
Closing this. I prefer the proposal at #42
