### ISSUE TITLE
Use tags as equ values

### ISSUE THREAD

**Issue by arnaucastellvi** [Fubukimaru/asMSX#34]
The tags are fixed values, and the EQU too, then:
I think that, can use tags (pointers) as a value in EQUs, should be useful to precalculate other offsets ans sizes.
For example:
DATA: DW 1,2,3,4...etc
DATASIZE: db (DATASIZE - DATA)/2
LD HL,DATASIZE
LD A,(HL)
SLA A ; A*=2

Should be...

DATA: DW 1,2,3,4,...etc
DATAEND:
SIZE equ (DATAEND-DATA)/2 ;Random precompile operation using tags
ld A,SIZE*2 ; A random precompile operation using EQU

**Comment by theNestruo** [comment]
I think it's already possible. Furthermore, you can use `$` so the second label would be unnecessary:
```
TXT_16KB_RAM_REQUIRED:
	.db	"16KB RAM REQUIRED"
	TXT_16KB_RAM_REQUIRED_LENGTH equ $ - TXT_16KB_RAM_REQUIRED
```
(actual examples [here](https://github.com/theNestruo/msx-wrally/blob/master/src/rally_rom_data.asm#L81))

**Comment by Fubukimaru** [comment]
From the manual:
```
$ is is a special read-only variable. During assembly of program, $ is replaced with memory address of next opcode or data, during execution it is equal to PC register.
```

So it would be something like:
```
DATA: DW 1,2,3,4,...etc
SIZE equ ($-DATA)/2 ; Number of words in DATA
ld A,SIZE*2 ; A random precompile operation using EQU
```

It's working, so I'll close this issue. Thanks!
