### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by oboroc** [Fubukimaru/asMSX#40]
Folks, I'd like to get an agreement on the code formatting style and formalize it in an [.editorconfig](https://editorconfig.org/) file in the project.

## Tabs or spaces for formatting?

Tabs are neat, but if people use different settings in their editors, end results may look not so great.

Spaces are a bit annoying, but they guarantee source looks the same for everyone.

In vim and many other editors, it is easy to highlight tabs so they are clearly visible vs spaces.

## For tabs, do we set tab to be equal to 2, 4 or 8 spaces?
If we decide to use tabs, how should we set our editors?

## Do we use Microsoft or K&R brackets?
Lots of examples in this [wikipedia article](https://en.wikipedia.org/wiki/Indentation_style#Styles).
K&R brackets:
```
function max(int a, int b) {
    int r;
    if (a > b) {
        r = a;
        printf("%d > %d\n", a, b);
    } else if (a < b) {
        r = b;
        printf("%d < %d\n", a, b);
    } else if (a == b) {
        r = a;
        printf("%d == %d\n", a, b);
    }
    return r;
}
```

Microsoft brackets:
```
function max(int a, int b)
{
    int r;
    if (a > b)
    {
        r = a;
        printf("%d > %d\n", a, b);
    }
    else if (a < b)
    {
        r = b;
        printf("%d < %d\n", a, b);
    }
    else if (a == b)
    {
        r = a;
        printf("%d == %d\n", a, b);
    }
    return r;
}
```

## Do we want to use basic C89 types only or are we ok with C99 <stdint.h> types: int8_t, int16_t, int32_t, int64_t and uint8_t, uint16_t, uint32_t, uint64_t.

There is probably more stuff like this, but the above questions are a good start for a coding style document. We can always expand it later.

**Comment by oboroc** [comment]
My personal preferences:
* tabs at 4 spaces
* Microsoft brackets
* C99 types

**Comment by Fubukimaru** [comment]
My preferences:

- Tabs at 4 spaces
- Both work for me

About types, which is the difference?

**Comment by oboroc** [comment]
C89 types work on older compilers like Borland C++ and Watcom C++. Signed or unsigned for plain char and sizeof(int) depends on the platform.

C99 types require a more recent compiler (2000+) and type is same signedness and size.

OpenBSD kernel source uses C89 types. Linux kernel source uses C99 types.

**Comment by Fubukimaru** [comment]
The advantage I see is that you mark how many bits are you using for each element, right?

Then C99 is fine for me.

**Comment by oboroc** [comment]
Ok! I'll add a coding style document to asMSX repository and then close this "issue".

**Comment by oboroc** [comment]
I opened a PR https://github.com/Fubukimaru/asMSX/pull/41 to add coding style document and also formatted source to match coding style guidelines. Please accept PR and close this issue.
