### ISSUE TITLE
Cross compile for MacOS

### ISSUE THREAD

**Issue by oboroc** [Fubukimaru/asMSX#43]
@Fubukimaru, you are using Linux and MinGW to cross-compile to Windows.

Can you also cross-compile for MacOS? I can help setting up the toolchain if you want. It is a combination of [osxcross](https://github.com/tpoechtrager/osxcross) and MacOS SDK.

**Comment by Fubukimaru** [comment]
I compiled it for OSX (took like 5 minutes to set it up and compile it lol).

I have sent it to a friend for testing.

**Comment by Fubukimaru** [comment]
I changed from 32 bits to 64 bits for OSX and it works nicely :).

Should we do a release with it?

**Comment by oboroc** [comment]
Hi Fubu, you can, why not? Call it something like 0.19.1. Changelog would be addition of gtest for test coverage, bugfix for error handling in vim and the new support for macOS.

Please note, Apple doesn't call it's OS "Mac OS X" anymore, it calls it "macOS", exact characters. So for file name may be use asmsx_x.y.z_macos.zip? We can get fancier in future if there is time and desire and make a dmg file with nice icons (native macOS distribution format). But for now plain compiled binary is very nice!

**Comment by Fubukimaru** [comment]
Done

https://github.com/Fubukimaru/asMSX/releases/tag/0.19.1

I'm closing this. Not a very big fan of fancy stuff, but if we know how to do it and it is not very complex, we can :).
