### ISSUE TITLE
INCBIN + SKIP + SIZE don't works fine with MEGAROM Pages

### ISSUE THREAD

**Issue by nataliapc** [Fubukimaru/asMSX#55]
If we try to add an `.incbin` directive around the end of a megarom page, the `SIZE` parameter (of the `incbin`) don't matters and a _**"megaROM subpage overflow"**_ message is show. Even if SIZE is set to 1.

**Comment by Fubukimaru** [comment]
Hello Natalia,

Could you provide me a minimum example code to work with? Thanks :)

**Comment by nataliapc** [comment]
```
.megarom	Ascii8

[...]

.SUBPAGE 4 AT $A000
    .ds 2048
    .incbin "resources/file_4096bytes.bin" 0 2048

```

**Comment by Fubukimaru** [comment]
Hello Natalia,

Sorry for the delay replying.

I have tested this code:
```
.bios
.megarom	Ascii8

.SUBPAGE 4 AT $A000
    .ds 4096
    .INCBIN "test.bin" SKIP 1 SIZE 4096
```

Using a randomly generated test.bin of length 8KB. This minimal example works for me. It doesn't complain. However it does complain from one thing, .INCBIN requires for SKIP and SIZE keywords to be used. `.INCBIN "test.bin" 1 4096` is not allowed.

I assume that you're using it this way and this was just a problem of writing it.

On the other hand, do you have the lastest version of asMSX? 

I hope we can fix it :)

**Comment by nataliapc** [comment]
Are you right, I'm missing SKIP/SIZE keywords.

Thanks!

**Comment by Fubukimaru** [comment]
Does it work now?

**Comment by nataliapc** [comment]
Works fine ^^

**Comment by Fubukimaru** [comment]
Perfect! I'm closing the issue :)
