### ISSUE TITLE
Unreachable code error

### ISSUE THREAD

**Issue by nataliapc** [Fubukimaru/asMSX#56]
I receive this error:
```
Assembling labels, calls and jumps
line 65: unreachable address

```
Unreachable code should be a warning message, not an error one.
Because we could be using self modified code, or just accesing the code using `JP [HL]`.
Being an error message the legit code can't be compiled.

**Comment by Fubukimaru** [comment]
Hello Natalia,

Is it already ok?

**Comment by nataliapc** [comment]
It's ok, thanks Fubukimaru

**Comment by Fubukimaru** [comment]
Perfect :)
