### ISSUE TITLE
[Wishlist] Implement Macros

### ISSUE THREAD

**Issue by ghost** [Fubukimaru/asMSX#6]
Implement macros in asMSX. Just that.

**Comment by oboroc** [comment]
Can you elaborate with example source code with macros you want and how they should be processed/expanded?

**Comment by Fubukimaru** [comment]
We could go for a C-like macro. I believe that there is an assembler/crossassembler with macros, right? For the sake of easy of usage (if someone adopts this coming from the other assembler), we should imitate the syntax as long as it's coherent  with what we have.

About the processing:
I would go for a simple expansion in which the code is copied in place and variables are substituted by the actual values.

This way we can't have a macro of a macro, but it's simple enough. What do you think?

I got the idea from this post: https://www.msx.org/forum/msx-talk/development/compare-assemblers?page=1 (Metalion)

**Comment by oboroc** [comment]
asMSX as-is has multiple marcos. I'll try to come up with a comprehensive example asm file that shows them all.

I could try to implement extra macros as external separate pre-processor. Kind of like CPP pre-processor in C. If it works well, it could eventually be added to main source/binary.

What I need is a sample source code with macro, and then same source code with macro expanded. This way it will be possible to see what we want to achieve.

**Comment by Fubukimaru** [comment]
I have no code for this. Maybe we can ask interested people so they provide what they would like to have.

**Comment by nataliapc** [comment]
Maybe something like:

```
;******************************************************************************
; DEBUG_BORDERCOLOR
;******************************************************************************
	.macro DEBUG_BORDERCOLOR value
		push af
		ld  a,value
		out ($99),a
		ld  a,$87
		out ($99),a
		pop  af
	.endm

```

**Comment by Fubukimaru** [comment]
I think that what @nataliapc proposes could be done as @oboroc said. An external preprocessor or a preprocessor step (like the 3 we already have) to do the substitution.

I'll consider it after we fix the Issue #4

**Comment by Fubukimaru** [comment]
AS80 macro example

```
print   macro   
    ld  de,\1
    ld  c,_STROUT
    call    DOS
    endm

```

**Comment by Fubukimaru** [comment]
SJASM is as @nataliapc said:

```
  macro BDOS fun       ; macro definition
  ld c,fun
  call 5
  endmacro
  BDOS 5               ; macro call
```

**Comment by Fubukimaru** [comment]
In compass:
```
BDOS: macro @fun
  ld c, @fun
  call 5
 endm
```

**Comment by jamque** [comment]
Rodnay Zaks uses Cromeco Z80 Macro Assembler
Book: http://www.z80.info/zip/zaks_book.pdf Programming th Z80
How to use Cromeco z80: https://www.z80cpu.eu/mirrors/www.autometer.de/unix4fun/z80pack/ftp/cromemco/Cromemco%20Z80%20Macro%20Assembler%20023-0039%20197810.pdf
Page 65

**Comment by Fubukimaru** [comment]
The commit https://github.com/Fubukimaru/asMSX/commit/19ee7397f5300cf233e8c1591ef31cec308d1bcc adds the following:
- 0 to 10 parameters on a macro
- Proper error messaging for possible parameter issues (more than possible registered, parameters given in a call are not enough or are too much.

We have decided to follow the Cromeco syntax at the moment, but I could implement easily other macro syntax (mainly compass and sjasm).

**Comment by Fubukimaru** [comment]
I have been thinking that allowing to use macros before definition doesn't make sense. 

For instance, in C you have to define at least the header before using it. For the moment I'm closing this.
