### ISSUE TITLE
Update Bison debugging

### ISSUE THREAD

**Issue by Fubukimaru** [Fubukimaru/asMSX#64]
YYPRINT is outdated and doesn't work. https://www.gnu.org/software/bison/manual/bison.html#The-YYPRINT-Macro

**Comment by duhow** [comment]
I think `yyprint` is not used in in any place, as per the compiler warnings.
Would be better just to remove it and use functions to add logging?
```
src/dura.y:4303:1: warning: 'yyprint' defined but not used [-Wunused-function]
 4303 | yyprint (file, type, value)
      | ^~~~~~~
```

**Comment by Fubukimaru** [comment]
It is not used because it's how the old debugging system works. We need to update it as mentioned in the URL in the first message.

It's not the regular debugging system. It debugs the grammar, not the code itself. So adding logging to our functions would be a high cost and not very benefitial.

**Comment by duhow** [comment]
What about https://github.com/rxi/log.c ?

**Comment by Fubukimaru** [comment]
Cool package, I'll consider it for general logging! Not sure about colors as the text usually gets postprocessed in an IDE.

On the other hand, this issue is about the deprecated way to debug Bison. We have to use the new way of setting the debugging on as commented here: https://www.gnu.org/software/bison/manual/bison.html#The-YYPRINT-Macro

**Comment by Fubukimaru** [comment]
https://github.com/Fubukimaru/asMSX/commit/418317e91580e6dc88393ef79b461f9302354f23

Done :)
