### ISSUE TITLE
sometimes "undefined identifier"

### ISSUE THREAD

**Issue by jamque** [Fubukimaru/asMSX#76]
Tested with v.1.0.0-3-ga2f37e0
Demo code
**File: TEST.ASM**
```asm
	ZILOG
	nop
	;ld	A,(RUNEVENTS_EVENTSDONE)
;------------------------------------
; RAM
;------------------------------------
	PAGE	3
___RAM___:
PILA0:
	ds	256
PILA:	byte

	INCLUDE "RAM/RUNEVENTS.RAM"
```
**File: RUNEVENTS.RAM**
```asm
;RUNEVENTS Variables en RAM

RUNEVENTS_MAX_EVENTSDONE	equ	EVENTS_TOTAL
RUNEVENTS_EVENTSDONE:		ds	2 * RUNEVENTS_MAX_EVENTSDONE
RUNEVENTS_EVENTSDONE_END:
```
Beware EVENTS_TOTAL not defined, but...
Output: 
```
Parsing file TEST.ASM
Using standard Zilog syntax
Expanding system macros
Assembling source file TEST.ASM
Assembling labels, calls and jumps
Binary file TEST.z80 saved
Symbol file TEST.sym saved
Completed in 0.03 seconds
```
TEST.SYM
No symbols from INCLUDE file
```asm
; Symbol table from TEST.ASM
; generated by asMSX v.1.0.0-3-ga2f37e0

; global and local labels
C000h ___RAM___
C000h PILA0
C100h PILA
```

uncommend line 3 from TEST.ASM
EVENTS_TOTAL stills not defined, but there is an error about RUNEVENTS_EVENTSDONE
Output: 
```
Parsing file TEST.ASM
Using standard Zilog syntax
Expanding system macros
Assembling source file TEST.ASM
Assembling labels, calls and jumps
TEST.ASM, line 3: undefined identifier
```

**Comment by Fubukimaru** [comment]
There is something wrong with the include. It's not including `RUNEVENTS.RAM`. 

I cannot reproduce this on linux. I'm going to test it on windows.

**Comment by Fubukimaru** [comment]
This happens because last include doesn't have CRLF (^M).

So it gets to EOF wihout matching the include for some reason. I'm going to check it.

Quick fix: always have an \n at the end of your file.
Quicker fix: use linux :P

**Comment by Fubukimaru** [comment]
Fixed here: https://github.com/Fubukimaru/asMSX/commit/54dfeb50b892af712d789aec04ac8b5ccb4bc5af
