### ISSUE TITLE
No problems

### ISSUE THREAD

**Issue by jamque** [Fubukimaru/asMSX#83]
This Issue is for celebrate that I have been used asmsx in the last 24 hours and there is no more Issues to report.
Please keep this Issue Open until a new Issue comes to this repository.
![there are no accidents](https://i.imgflip.com/3aj1vh.jpg)

**Comment by Fubukimaru** [comment]
Pray for 0 issues until 1.1.0

**Comment by duhow** [comment]
Closing, since multiple problems were reported. 😂
