### ISSUE TITLE
Add ARMv6h cross-compilation

### ISSUE THREAD

**Issue by Fubukimaru** [Fubukimaru/asMSX#85]
Probably asMSX will be included in the very beautiful [MSXVR](https://msxvr.com/) which is based on a Raspberry Pi board. Therefore we need to have a release cross-compilation for this architecture.

**Comment by Fubukimaru** [comment]
https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads

**Comment by Fubukimaru** [comment]
https://aur.archlinux.org/packages/gcc-arm-none-eabi-bin/

**Comment by duhow** [comment]
Do you mean it is able to run Linux ELF `armel` programs?
You can implement this build generation in Github Actions to make it universal :)

**Comment by Fubukimaru** [comment]
So, github is able to generate it directly? It would be cool that Github would build the release zips when a release is defined. Is this possible?

I'm now trying to add `arm-linux-gnueabihf-gcc` building step.

**Comment by duhow** [comment]
Rather than defining a new "step", you should be able to change CC and FLAGS by calling them in the `make` command or via environment. That's how the cross-compile projects are done.

```
root@predator:/asMSX# make CC=gcc-arm-none-eabi-10-2020-q4-major/bin/arm-none-eabi-gcc LDFLAGS="-specs=nosys.specs"
gcc-arm-none-eabi-10-2020-q4-major/bin/arm-none-eabi-gcc src/dura.tab.c src/lex.yy.c src/lex.parser1.c src/lex.parser2.c src/lex.parser3.c src/lex.parser4.c src/asmsx.c src/labels.c -oasmsx -lm -O2 -Os -s -Wall -Wextra -DVERSION=\"1.0.0-39-g0eb102d\" -DDATE=\"2021-01-20\" -DLINUX -specs=nosys.specs

root@predator:/asMSX# ls -la
total 348
drwxr-xr-x 10 root root   4096 Jan 28 17:46 .
drwxr-xr-x  1 root root   4096 Jan 28 17:32 ..
drwxr-xr-x  8 root root   4096 Jan 28 17:46 .git
-rw-r--r--  1 root root    103 Jan 28 17:32 .gitattributes
drwxr-xr-x  3 root root   4096 Jan 28 17:32 .github
-rw-r--r--  1 root root    488 Jan 28 17:32 .gitignore
-rw-r--r--  1 root root   5370 Jan 28 17:32 CHANGELOG.md
-rw-r--r--  1 root root  35796 Jan 28 17:32 LICENSE.md
-rw-r--r--  1 root root   2586 Jan 28 17:38 Makefile
-rw-r--r--  1 root root   1871 Jan 28 17:32 README.md
-rwxr-xr-x  1 root root 282608 Jan 28 17:46 asmsx
drwxr-xr-x  3 root root   4096 Jan 28 17:32 build
drwxr-xr-x  3 root root   4096 Jan 28 17:32 code
drwxr-xr-x  2 root root   4096 Jan 28 17:32 doc
drwxr-xr-x  6 root root   4096 Jan 28 17:33 gcc-arm-none-eabi-10-2020-q4-major
drwxr-xr-x  2 root root   4096 Jan 28 17:32 ref
drwxr-xr-x  2 root root   4096 Jan 28 17:35 src

root@predator:/asMSX# file asmsx 
asmsx: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, stripped
```

And yes, release can be generated from Github Actions.

**Comment by Fubukimaru** [comment]
Cool! Two things: 

Instead of none could we use linux? I learned today that none is to compile bare metal executables.

And, I would like to generate a new asmsx.arm or something like that, so that the `make release` build both.
