### ISSUE TITLE
last binary windows version does not work at all

### ISSUE THREAD

**Issue by albmef** [Fubukimaru/asMSX#95]
hi 

the last windows-x86 build does not work :
"
PS C:\Users\alban\Desktop\MSX\asmsx-win-x86_64> .\asmsx.exe
PS C:\Users\alban\Desktop\MSX\asmsx-win-x86_64>
"

the previous build works :
"
PS C:\Users\alban\Desktop\MSX\asmsx_1.0.0-3-ga2f37e0\asmsx_1.0.0-3-ga2f37e0_win32> .\asmsx.exe
-------------------------------------------------------------------------------
 asMSX v.1.0.0-3-ga2f37e0. MSX cross-assembler. asMSX Team. [2020-12-07]
-------------------------------------------------------------------------------

Syntax: asMSX [-z|-s|-vv] [file.asm]
PS C:\Users\alban\Desktop\MSX\asmsx_1.0.0-3-ga2f37e0\asmsx_1.0.0-3-ga2f37e0_win32>
"

i got a working build here
https://www.msx.org/downloads/asmsx-version-10

best regards
Alban

**Comment by Fubukimaru** [comment]
Hello Alban,

Could you try this one?
[asmsx-win-x86_64.zip](https://github.com/Fubukimaru/asMSX/files/7659692/asmsx-win-x86_64.zip)
I have built it now with the latest commits.

Thanks for reporting!

**Comment by duhow** [comment]
@Fubukimaru are the builds from GitHub Actions not working properly?

**Comment by Fubukimaru** [comment]
@duhow I tried it in linux and it asked for some DLLs. Maybe that's the issue. We will have to check at some point when we can meet ;)

**Comment by albmef** [comment]
hmmm i'm really sorry Fubukimaru this one does not work either 
no banner, nothing

"
PS C:\Users\alban\Desktop\MSX\asmsx-win-x86_64> .\asmsx.exe
PS C:\Users\alban\Desktop\MSX\asmsx-win-x86_64>
"

if you want me to perform some test feel free to ask
best regards
Alban

**Comment by Fubukimaru** [comment]
[asmsx.zip](https://github.com/Fubukimaru/asMSX/files/7666383/asmsx.zip)

I believe that I have sent you the same exe. Try this one.

**Comment by albmef** [comment]
@Fubukimaru 
this one works i'm able to assemble my code and test the binary using bluemsx
please proceed with updating the repo and close this issue. thanks for your support
best regards
Alban

PS C:\Users\alban\Desktop\MSX\alban> .\asmsx.exe
-------------------------------------------------------------------------------
 asMSX v.1.0.1-14-g11f8ce9. MSX cross-assembler. asMSX Team. [2021-10-20]
-------------------------------------------------------------------------------

Syntax: asMSX [-z|-s|-vv] [file.asm]
PS C:\Users\alban\Desktop\MSX\alban> .\asmsx.exe .\loop.asm
-------------------------------------------------------------------------------
 asMSX v.1.0.1-14-g11f8ce9. MSX cross-assembler. asMSX Team. [2021-10-20]
-------------------------------------------------------------------------------

Parsing file .\loop.asm
Expanding Macros
DONE Expanding Macros
Expanding REPT
Assembling source file .\loop.asm
Assembling labels, calls and jumps
Binary file .\loop.bin saved
cas file .\loop.cas
Audio file .\loop.wav saved [8.87 sec]
Symbol file .\loop.sym saved
Completed in 0.14 seconds
PS C:\Users\alban\Desktop\MSX\alban>

**Comment by Fubukimaru** [comment]
Thanks for the confirmation :).

I'll leave this open so that we check the automatically built one!

**Comment by duhow** [comment]
@albmef Just to ensure, does this Artifact work for you? https://github.com/Fubukimaru/asMSX/suites/4105922009/artifacts/104793485

(from latest build https://github.com/Fubukimaru/asMSX/actions/runs/1362762027)

@Fubukimaru Build process did not change, we're building with Linux GCC as before.

**Comment by duhow** [comment]
Ok, managed to reproduce... Builds done on Github Actions with runner `windows-latest` (using `msbuild`) have this requirement. I forgot we were building Windows builds with this 😅

```
07/12/2021  08:38           208.384 asmsx.exe
17/08/2021  19:49           291.840 asmsx_1.exe
20/10/2021  08:53           291.840 asmsx_2.exe

TrID/32 - File Identifier v2.24 - (C) 2003-16 By M.Pontello
Definitions found:  12134
Analyzing...

File: asmsx.exe
 48.1% (.EXE) Win32 Executable MS Visual C++ (generic) (31206/45/13)

File: asmsx_1.exe
 61.7% (.EXE) Win64 Executable (generic) (27624/17/4)

File: asmsx_2.exe
 64.5% (.EXE) Win32 Executable MS Visual C++ (generic) (31206/45/13)
```

**Comment by duhow** [comment]
Also @Fubukimaru you should not update the Release Asset with the latest version, but instead with the same commit version, or just create a new tag / release with this fix.
